networks:
  mda:
    external:
    name: mda
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - mda
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
      - 9091:9091
    volumes:
      - ./data/kafka:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS: ENABLE
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://0.0.0.0:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://100.111.43.19:9091
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
    networks:
      - mda

  kafka-adapter:
    image: telefonica/prometheus-kafka-adapter:1.8.0
    ports:
      - 9093:8080
    environment:
      SERIALIZATION_FORMAT: json
    depends_on: [kafka]
    networks:
      - mda

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 9095:3000
    networks:
      - mda

  roach:
    image: cockroachdb/cockroach:v21.2.7
    command: start-single-node --insecure --listen-addr=0.0.0.0
    volumes:
      - ./data/cockroach:/cockroach/cockroach-data
    ports:
      - 9094:8080
      - 26257:26257
    networks:
      - mda
