#+TITLE: Wielowymiarowa analiza danych
 #+author: Hubert Baran 164141, Patryk Gronkiewicz 164157
 #+email: 164141@stud.prz.edu, 164157@stud.prz.edu.pl
 #+language: pl
 #+latex_class: report

* Użyte oprogramowanie
1. ETL --- [[https://kafka.apache.org][Apache Kafka]][fn:kafka]
   + W celu ładowania danych z Prometheusa użyto odpowiedniego [[https://github.com/Telefonica/prometheus-kafka-adapter][adaptera]][fn:adapter] stworzonego przez firmę Telefónica.
   + Klient Kafki --- [[https://github.com/confluentinc/confluent-kafka-python][Confluent]][fn:confluent]
2. Data warehouse --- [[https://www.cockroachlabs.com/][CockroachDB]][fn:cockroach] (kompatybilny z PostgreSQL)
3. Zarządzanie usługami --- [[https://ww.wdocker.com][Docker]][fn:docker]
4. Tworzenie wykresów --- [[https://grafana.com/][Grafana]][fn:grafana]
5. Źródło danych --- [[https://prometheus.io][Prometheus]][fn:prometheus]

[fn:kafka][[https://kafka.apache.org]]
[fn:confluent]https://github.com/confluentinc/confluent-kafka-python
[fn:cockroach]https://www.cockroachlabs.com/
[fn:docker]https://www.docker.com
[fn:grafana]https://grafana.com/
[fn:prometheus]https://prometheus.io
[fn:adapter]https://github.com/Telefonica/prometheus-kafka-adapter
* Uruchomienie projektu
** Instalacja zależności
Cały projekt można podzielić na trzy kluczowe elementy:
1. Usługi zewnętrzne;
2. Transformacje danych w ETL;
3. Analiza danych przetworzonych.

Pierwszy element jako jedyną zależność posiada Dockera. Dwie następne natomiast opierają się o Pythona w wersji $\geq 3.8$. Całą instrukcję instalacji Dockera można znaleźć pod [[https://docs.docker.com/get-docker/][tym adresem]][fn:docker-installation]. Po zainstalowaniu oraz wejściu do folderu głównego wystarczy uruchomić polecenie
#+begin_src shell-script :eval never
docker compose up
#+end_src
W przypadku braku podkomendy ~compose~ należy pobrać ~docker-compose~ z repozytorium Pythona przez komendę oraz uruchomić usługi
#+begin_src shell-script :eval never
pip install -U docker-compose
docker-compose up
#+end_src
W celu wyłączenia usług należy na klawiaturze wcisnąć =Ctrl= + =C=.

[fn:docker-installation] https://docs.docker.com/get-docker/

Pozostałe części projektu można przygotować do uruchomienia uruchomienie następujących komend (instrukcje dla Linuxa, dla Windowsa zmienia się jedynie pierwsza komenda).
#+begin_src shell-script :eval never
source .venv/bin/activate.sh
pip install -r requirements.txt
python FOLDER/main.py
#+end_src
Przy czym =FOLDER= należy zastąpić odpowiednią paczką, którą chcemy uruchomić w danym momencie.
** Uruchomienie
* Implementacja
** Generowanie danych
** ETL
*** Eksport danych z Prometheusa
*** Transformacje danych w Pythonie
*** Ładowanie danych do CockroachDB
** Analiza danych
*** Machine Learning
